name: Run Tests
on:
  workflow_run:
    workflows: 
      - "Terraform Plan + Apply"
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  TerraformTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Apply
        run: echo "triggered :)"
