name: Terraform Plan + Apply
on:
  workflow_dispatch:

jobs:
  TerraformDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.TERRAFORM_ROLE_ARN }}
          role-session-name: TF-OIDCSession
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
  
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Plan
        run: terraform plan -no-color
