name: Test Checkout
on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  TestWorkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: redja-s/app-deployment

      - name: Test Checkout successful
        run: ls